var width = 1200;
var height = 700;
var svg = d3.select("#svgcontainer3")
    .append('svg')
    .attr("width", width)
    .attr("height", height);
//svg.append("line")
//    .attr("x1", 100)
//    .attr("y1", 100)
//    .attr("x2", 200)
//    .attr("y2", 200)
//    .style("stroke", "rgb(255,0,0)")
//    .style("stroke-width", 2);
svg.append("rect")
    .attr("id", "r20652")
    .attr("x", 100)
    .attr("y", 80)
    .attr("rx", 10)
    .attr("ry", 10)
    .attr("opacity","0.2")
    .attr("width",  "20%")
    .attr("height", "70%")
    .attr("fill", "purple");
//d3.select('svg')
svg.append("text")
    .attr("x", "35")
    .attr("y", "50")
    //.attr("dy", ".35em")
    .attr("font-family", "sans-serif")
    //.attr("text-anchor","middle")
    .style("font-weight","bold")
    //.style("text-anchor","end")    
    .style("font-size","40px")
    .style("fill", "purple")
    .text("NTC-20652 - Metodología");